name: Reusable CI/CD for Node.js Fastify

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '22.x'
        description: 'Node version'
      dockerfile-path:
        required: false
        type: string
        default: './Dockerfile'
        description: 'Path to the Dockerfile'
      pre-release:
        required: false
        type: boolean
        default: false
        description: 'Only deploy in pre-release versions'

jobs:
  lint:
    if: ${{ !inputs.pre-release }}
    uses: ./.github/workflows/node-lint.yml
    with:
      node-version: ${{ inputs.node-version }}

  test:
    needs: [lint]
    if: ${{ !inputs.pre-release }}
    uses: ./.github/workflows/node-test.yml
    with:
      node-version: ${{ inputs.node-version }}

  docker-publish:
    needs: [test]
    uses: ./.github/workflows/docker-publish.yml
    with:
      dockerfile-path: ${{ inputs.dockerfile-path }}
