name: Node.js Test

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '22.x'
        description: 'Versión de Node.js a utilizar'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Tests
        run: npm test
